# Generated by Django 4.0.4 on 2022-05-11 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_involucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='involucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='pokemon.pokemon'),
        ),
    ]
