# Generated by Django 4.0.4 on 2022-05-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_alter_pokemon_involucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('forcas', models.ManyToManyField(to='pokemon.tipo')),
                ('fraquezas', models.ManyToManyField(to='pokemon.tipo')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='tipos',
            field=models.ManyToManyField(to='pokemon.tipo'),
        ),
    ]
