# Generated by Django 4.0.4 on 2022-05-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_alter_pokemon_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='forcas',
            field=models.ManyToManyField(blank=True, to='pokemon.tipo'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='fraquezas',
            field=models.ManyToManyField(blank=True, to='pokemon.tipo'),
        ),
    ]
