# Generated by Django 4.0.4 on 2022-05-31 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_remove_tipo_fraquezas_alter_tipo_cor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='fraquezas',
            field=models.ManyToManyField(blank=True, to='pokemon.tipo', verbose_name='Fraquezas'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='forcas',
            field=models.ManyToManyField(blank=True, to='pokemon.tipo', verbose_name='Forças'),
        ),
    ]
