# Generated by Django 4.0.4 on 2022-05-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_tipo_fraquezas_alter_tipo_forcas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='fraquezas',
        ),
        migrations.AlterField(
            model_name='tipo',
            name='forcas',
            field=models.ManyToManyField(blank=True, related_name='fraco_contra', to='pokemon.tipo', verbose_name='Forças'),
        ),
    ]
