# Generated by Django 4.0.4 on 2022-06-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0010_remove_tipo_fraquezas_alter_tipo_forcas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
